### ISSUE TITLE
GOTR Tiles

### ISSUE THREAD

**Issue by Nick2bad4u** [jamiegyoung/runemarkers#138]
Here are tiles I made for Guardians of the Rift

[{"regionId":14484,"regionX":6,"regionY":26,"z":0,"color":"#BB00FF00","label":"Mine"},{"regionId":14484,"regionX":21,"regionY":16,"z":0,"color":"#BB00FF00","label":"Mine"},{"regionId":14484,"regionX":9,"regionY":31,"z":0,"color":"#BB00FF00","label":"Portal"},{"regionId":14484,"regionX":24,"regionY":31,"z":0,"color":"#BB00FF00","label":"Cell"},{"regionId":14484,"regionX":25,"regionY":15,"z":0,"color":"#BB00FF00","label":"Runes"},{"regionId":14484,"regionX":38,"regionY":31,"z":0,"color":"#BB00FF00","label":"Cell"},{"regionId":14484,"regionX":19,"regionY":21,"z":0,"color":"#BB00FF00","label":"SW"},{"regionId":14484,"regionX":43,"regionY":31,"z":0,"color":"#BB00FF00","label":"East"},{"regionId":14484,"regionX":31,"regionY":30,"z":0,"color":"#BB00FF00","label":"Power Up"},{"regionId":14484,"regionX":50,"regionY":31,"z":0,"color":"#BB00FF00","label":"Climb"},{"regionId":14484,"regionX":52,"regionY":31,"z":0,"color":"#BB00FF00","label":"Climb"},{"regionId":14484,"regionX":31,"regionY":15,"z":0,"color":"#BB00FF00","label":"South"},{"regionId":14484,"regionX":56,"regionY":26,"z":0,"color":"#BB00FF00","label":"Mine"},{"regionId":14484,"regionX":6,"regionY":37,"z":0,"color":"#BB00FF00","label":"Mine"},{"regionId":14484,"regionX":43,"regionY":21,"z":0,"color":"#BB00FF00","label":"SE"},{"regionId":14484,"regionX":34,"regionY":16,"z":0,"color":"#BB00FF00","label":"Cells"},{"regionId":14484,"regionX":35,"regionY":16,"z":0,"color":"#BB00FF00","label":"Cells"},{"regionId":14484,"regionX":27,"regionY":15,"z":0,"color":"#BB00FF00","label":"Craft"},{"regionId":14484,"regionX":28,"regionY":15,"z":0,"color":"#BB00FF00","label":"Craft"},{"regionId":14484,"regionX":27,"regionY":14,"z":0,"color":"#BB00FF00","label":"Craft"},{"regionId":14484,"regionX":28,"regionY":14,"z":0,"color":"#BB00FF00","label":"Craft"}]

**Comment by jamiegyoung** [comment]
For the "Mine 160~" tile, does it scale with mining level? If so it may not be the best idea to keep that label

**Comment by Nick2bad4u** [comment]
No it doesn't, I should probable just make it "mine"

**Comment by Nick2bad4u** [comment]
Just to add what the tiles look like:

https://gyazo.com/63f7deab47d82cd838ce1dfb6b4900be
![image](https://user-images.githubusercontent.com/20943337/219885139-8d3e6765-7344-4264-b8c8-103095c578b8.png)


I'm thinking about adding the tiles for each Runecrafting altar as well, but I am not sure that would qualify at GOTR tiles since they would show even if not doing GOTR. So, I left them out.
