### ISSUE TITLE
refactor: missing chamber of xerics (crabs) configuration

### ISSUE THREAD

**Issue by caerulescens** [jamiegyoung/runemarkers#338]
**What activity/boss are these tiles for**

Chamber of Xerics - Crabs

**Is this an edit to some already exisiting tiles, if so why?**

Yes, there is one crabs configuration that is missing from the title markers; I could probably supply them. 

**Are these tiles for a subcategory of the boss, e.g. 5:0 or 6:0**

N/A

**Do you have a recommended video guide for the activity/boss**

N/A

**Is there a source for these tiles, if so please link it below**

N/A

**Please paste the tile's JSON data below**
Right click export on the world map, use the [Runelite tile viewer](https://runelite.net/tile) to check they are correct:
```json

```

**Comment by caerulescens** [comment]
I'll add more details when I encounter the configuration again.

**Comment by jamiegyoung** [comment]
Hello! Just bumping this to see if you've got the tiles for this configuration, thanks!

**Comment by caerulescens** [comment]
I'll hop on sometime next week and find them.

**Comment by caerulescens** [comment]
@jamiegyoung 

For reference, this is the layout of the room that's missing tiles; I'm online right now, and I found the type of room. Also, I have already imported the runemarker tiles at this point, and other versions of the crab rooms show titles correctly. I'll figure out the easiest layout, and export the tiles. 

---

![2024-10-08_22-45-53](https://github.com/user-attachments/assets/621f49c4-6d5c-48f3-a3a3-231e4ba58c49)

**Comment by caerulescens** [comment]
Here's are 8 tiles that show the shortest path; I think it could be made more efficient, but at least the coordinates below are correct. Given the compass and the `x`, `y` positions, the best tiles can be inferred (meaning 'anchor')

![2024-10-08_23-18-35](https://github.com/user-attachments/assets/c4cd2b15-99e4-40aa-982f-1dcfb160150a)

```json
{"regionId":13139,"regionX":54,"regionY":42,"z":2,"color":"#FFFF0000"},{"regionId":13139,"regionX":40,"regionY":43,"z":2,"color":"#FFFF0000"},{"regionId":13139,"regionX":54,"regionY":43,"z":2,"color":"#FFFFFFFF"},{"regionId":13139,"regionX":51,"regionY":47,"z":2,"color":"#FF0000FF"},{"regionId":13139,"regionX":52,"regionY":49,"z":2,"color":"#FF0000FF"},{"regionId":13139,"regionX":54,"regionY":46,"z":2,"color":"#FF0000FF"},{"regionId":13139,"regionX":54,"regionY":47,"z":2,"color":"#FF00FF00"},{"regionId":13139,"regionX":41,"regionY":48,"z":2,"color":"#FF00FF00"}
```

**Comment by caerulescens** [comment]
@jamiegyoung AFAIK, this is the only version of crabs that's missing, but this version of crabs could be found for a different order of rooms within the raid. In this case, would the `x`, `y` coordinates be different? I imagine it would, and I'll scout more raids for this version of the crabs room.

**Comment by jamiegyoung** [comment]
Sorry for the delay, these have been added now, thanks again!
